### ISSUE TITLE
If there isn't an available toolchain CMake.js crashes with unhandlend rejection error

### ISSUE THREAD

**Issue by unbornchikken** [unbornchikken/cmake-js#20]
H:\arrayfire_js-master>node_modules\.bin\cmake-js
info CMD CONFIGURE
info RUN cmake "H:\arrayfire_js-master" --no-warn-unused-cli -G"Visual Studio 11
 2012 [arch] Win64" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_JS_INC="C:\Users\un\.cm
ake-js\node-x64\v0.12.4\src;C:\Users\un\.cmake-js\node-x64\v0.12.4\deps\v8\inclu
de;C:\Users\un\.cmake-js\node-x64\v0.12.4\deps\uv\include;H:\arrayfire_js-master
\node_modules\nan" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="0.12.4" -DNODE_A
RCH="x64" -DCMAKE_JS_LIB="C:\Users\un\.cmake-js\node-x64\v0.12.4\x64\node.lib" -
DAF_PATH="H:/v3"
Not searching for unused variables given on the command line.
CMake Error: Could not create named generator Visual Studio 11 2012 [arch] Win64

Generators
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 8 2005 [arch]  = Generates Visual Studio 2005 project files.
                                 Optional [arch] can be "Win64".
  Visual Studio 7 .NET 2003    = Generates Visual Studio .NET 2003 project
                                 files.
  Visual Studio 7              = Deprecated.  Generates Visual Studio .NET
                                 2002 project files.
  Visual Studio 6              = Deprecated.  Generates Visual Studio 6
                                 project files.
  Borland Makefiles            = Generates Borland makefiles.
  NMake Makefiles              = Generates NMake makefiles.
  NMake Makefiles JOM          = Generates JOM makefiles.
  Green Hills MULTI            = Generates Green Hills MULTI files
                                 (experimental, work-in-progress).
  MSYS Makefiles               = Generates MSYS makefiles.
  MinGW Makefiles              = Generates a make file for use with
                                 mingw32-make.
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files.
  CodeBlocks - NMake Makefiles = Generates CodeBlocks project files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - MinGW Makefiles   = Generates CodeLite project files.
  CodeLite - NMake Makefiles   = Generates CodeLite project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Eclipse CDT4 - MinGW Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - NMake Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
  Kate - MinGW Makefiles       = Generates Kate project files.
  Kate - NMake Makefiles       = Generates Kate project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Sublime Text 2 - MinGW Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - NMake Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.

ERR! OMG Process terminated: 1
Unhandled rejection Error: Process terminated: 1
    at ChildProcess.<anonymous> (H:\arrayfire_js-master\node_modules\cmake-js\li
b\cMake.js:367:24)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

**Comment by unbornchikken** [comment]
Fixed in 0.13.1
