### ISSUE TITLE
cmake-js binary cannot be found when an upper level project has cmake-js dependency.

### ISSUE THREAD

**Issue by unbornchikken** [unbornchikken/cmake-js#7]
If the main project has cmake-js as a dependency, you get: 
```
amelie@Samsung-550P7C ~/workspace/projetPFE $ npm install
|
> albers-core-module@1.0.0 install /home/amelie/workspace/projetPFE/node_modules/albers-core-module
> node ./node_modules/cmake-js/bin/cmake-js rebuild


module.js:340
    throw err;
          ^
Error: Cannot find module '/home/amelie/workspace/projetPFE/node_modules/albers-core-module/node_modules/cmake-js/bin/cmake-js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

If the main project has nan as a dependency, you get: 
```
info CMD BUILD
info RUN cmake --build "/home/amelie/workspace/projetPFE/node_modules/albers-core-module/build" --config Release
Scanning dependencies of target addon
[  5%] Building CXX object CMakeFiles/addon.dir/src/addon.cc.o
/home/amelie/workspace/projetPFE/node_modules/albers-core-module/src/addon.cc:2:10: fatal error: 'nan.h' file not found
#include <nan.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/addon.dir/src/addon.cc.o] Error 1
make[1]: *** [CMakeFiles/addon.dir/all] Error 2
make: *** [all] Error 2
ERR! OMG Process terminated: 2

```

But it works fine once your remove those dependencies.

**Comment by unbornchikken** [comment]
Fixed in v0.11.4. Please note that install scipt should be just `cmake-js rebuild` from now on.
